### ISSUE TITLE
Integration test fails intermittently

### ISSUE THREAD

**Issue by Bjvanminnen** [code-dot-org/dance-party#115]
`node test/integration/spriteDanceTest.js`

I've seen this test fail randomly a couple times in travis. I ran the command 5x locally against master, and it failed once. Would be good to get this passing consistently (or possibly disable the test if that's not an option).

```
>node test/integration/spriteDanceTest.js
TAP version 13
# Dance collision: every measures - rarer move second
ok 1 should be truthy
# Dance collision: every measures - rarer move first
not ok 2 should be truthy
  ---
    operator: ok
    expected: true
    actual:   false
    at: attempt (/Users/brent/git/dance-party/test/integration/spriteDanceTest.js:16:11)
    stack: |-
      Error: should be truthy
          at Test.assert [as _assert] (/Users/brent/git/dance-party/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/Users/brent/git/dance-party/node_modules/tape/lib/test.js:76:32)
          at Test.assert (/Users/brent/git/dance-party/node_modules/tape/lib/test.js:342:10)
          at Test.bound [as true] (/Users/brent/git/dance-party/node_modules/tape/lib/test.js:76:32)
          at attempt (/Users/brent/git/dance-party/test/integration/spriteDanceTest.js:16:11)
          at DanceParty.onPuzzleComplete [as onPuzzleComplete_] (/Users/brent/git/dance-party/test/helpers/runLevel.js:14:7)
          at DanceParty.fail (/Users/brent/git/dance-party/src/p5.dance.js:144:10)
          at Object.eval [as validationCallback] (eval at onInit (/Users/brent/git/dance-party/test/helpers/runLevel.js:24:34), <anonymous>:8:23)
          at DanceParty.draw (/Users/brent/git/dance-party/src/p5.dance.js:946:16)
          at p5Inst.draw (/Users/brent/git/dance-party/src/p5.dance.js:111:32)
  ...
# Dance collision: every seconds - rarer move second
ok 3 should be truthy
# Dance collision: every seconds - rarer move first
```

**Comment by joshlory** [comment]
@epeach are you still tracking this?

https://codedotorg.slack.com/archives/CC2QHV7SR/p1541002217194100

**Comment by epeach** [comment]
Closing for now. First set of test updates are merged in. Will re-open if issue persists.

**Comment by joshlory** [comment]
Still seems to be flakey, even with the latest fix:

https://travis-ci.org/code-dot-org/dance-party/builds/451160557

**Comment by joshlory** [comment]
Possible fix, migrating these to unit tests following the pattern in PR https://github.com/code-dot-org/dance-party/pull/222/#discussion_r232336174.

**Comment by epeach** [comment]
Closing after merging PR #304
